[tool.poetry]
name = "AdventOfCode"
version = "0.1.0"
description = "Solutions to Advent of Code puzzles"
authors = ["Andreas Midjord <midjord.andreas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
regex = "^2024.11.6"
numpy = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
ruff = "^0.8.0"
pyright = "^1.1.338"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
lint.fixable = ["ALL"]
lint.select = [
    "B",    # Bugbear
    "D",    # pydocstyle
    "E",    # pycodestyle
    "F",    # pyflakes
    "FLY",  # flynt (no static string.join)
    "I",    # isort
    "ISC",  # Implicit string concatenation
    "LOG",  # Logging
    "PIE",  # Pie
    "PT",   # pytest
    "Q",    # Quotes
    "TCH",  # Typecheck
    "UP",   # Pyupgrade
    "W",    # pycodestyle
]
lint.ignore = [
    "D100",  # Missing docstring in public module
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in `__init__` method
    "D203",  # 1 blank line required before class docstring
    "D417",  # Missing argument description for *args, **kwargs
    "D211",
    "D213",
    "ANN401",
]
[tool.ruff.lint.per-file-ignores]
"tests/**" = ["ANN"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(message)s"
